import React,{useEffect,useState}from"react";import{createRoot}from"react-dom/client";import{ArrowRight,Check,ChevronDown,Menu,Play,Quote,Star,X}from"lucide-react";import"./style.css";

const modules=[
 {n:"01",title:"Find the sharp edge",copy:"Turn broad experience into a precise promise people can immediately understand.",lessons:["Audience tension map","Offer thesis","Positioning teardown"]},
 {n:"02",title:"Build the offer",copy:"Shape the transformation, delivery model, and price into one coherent product.",lessons:["Outcome architecture","Scope boundaries","Pricing logic"]},
 {n:"03",title:"Create the campaign",copy:"Write a launch narrative that earns attention without manufacturing urgency.",lessons:["Message hierarchy","Launch assets","Email sequence"]},
 {n:"04",title:"Ship and learn",copy:"Launch with a useful measurement plan, then improve the next cycle.",lessons:["Live launch room","Signal dashboard","Post-launch review"]},
];
const testimonials=[{q:"I stopped selling a collection of services and started selling a clear result. My first cohort filled in nine days.",name:"Nina Patel",role:"Brand strategist"},{q:"The campaign system gave us structure without making the work sound generic. We doubled our previous launch revenue.",name:"Marcus Lee",role:"Creative educator"},{q:"Every lesson produced something we used immediately. I finished with a real offer, not another folder of notes.",name:"Elena Ruiz",role:"Independent designer"}];

function Countdown(){const [left,setLeft]=useState(8*24*60*60+13*60*60+42*60);useEffect(()=>{const id=setInterval(()=>setLeft(v=>Math.max(0,v-1)),1000);return()=>clearInterval(id)},[]);const d=Math.floor(left/86400),h=Math.floor(left%86400/3600),m=Math.floor(left%3600/60),s=left%60;return <div className="countdown" aria-label={`${d} days ${h} hours ${m} minutes ${s} seconds until enrollment closes`}>{[[d,"DAYS"],[h,"HRS"],[m,"MIN"],[s,"SEC"]].map(([v,l])=><div key={String(l)}><b>{String(v).padStart(2,"0")}</b><span>{l}</span></div>)}</div>}

function App(){const [nav,setNav]=useState(false),[open,setOpen]=useState(0),[modal,setModal]=useState(false),[step,setStep]=useState(1),[name,setName]=useState(""),[email,setEmail]=useState(""),[goal,setGoal]=useState("");const close=()=>{setModal(false);setStep(1)};const next=()=>{if(step===1&&name.trim()&&email.includes("@"))setStep(2);else if(step===2&&goal)setStep(3)};return <>
 <header><a className="logo" href="#top">LAUNCH<span>CRAFT</span></a><button className="nav-toggle" onClick={()=>setNav(!nav)} aria-label="Toggle navigation"><Menu/></button><nav className={nav?"open":""}><a href="#outcomes">Outcomes</a><a href="#curriculum">Curriculum</a><a href="#instructor">Instructor</a><a href="#pricing">Pricing</a></nav><button className="nav-cta" onClick={()=>setModal(true)}>Join the studio</button></header>
 <main id="top"><section className="hero"><div className="hero-copy"><p className="eyebrow">4-WEEK LIVE LAUNCH STUDIO · COHORT 06</p><h1>Build the launch <em>people remember.</em></h1><p className="dek">Turn what you know into a focused offer, a campaign with a point of view, and a launch you can repeat.</p><div className="hero-actions"><button className="primary" onClick={()=>setModal(true)}>Reserve your seat <ArrowRight/></button><a href="#curriculum"><Play/>See the curriculum</a></div><div className="proof"><div className="faces"><span>NP</span><span>ML</span><span>ER</span></div><p><b>4.9/5</b> from 180+ independent creatives</p></div></div><div className="hero-art"><div className="sticker">LIVE<br/>OCT 12</div><div className="launch-card"><span>FROM EXPERTISE</span><b>TO OFFER</b><i>04 WEEKS</i></div><p>Strategy, story, system, ship.</p></div></section>
 <section className="ticker"><div>POSITIONING ✦ OFFER DESIGN ✦ CAMPAIGN STORY ✦ LAUNCH SYSTEM ✦ POSITIONING ✦ OFFER DESIGN ✦ CAMPAIGN STORY ✦</div></section>
 <section className="outcomes" id="outcomes"><div><p className="eyebrow">WHAT CHANGES</p><h2>Leave with a launch system, not launch anxiety.</h2></div><div className="outcome-grid"><article><b>01</b><h3>A sharper offer</h3><p>Name the specific outcome, scope the work, and price it with conviction.</p></article><article><b>02</b><h3>A useful story</h3><p>Build messaging around the real tension your audience already feels.</p></article><article><b>03</b><h3>A repeatable launch</h3><p>Use a campaign rhythm you can adapt instead of rebuilding every time.</p></article></div></section>
 <section className="curriculum" id="curriculum"><div className="section-intro"><p className="eyebrow">THE CURRICULUM</p><h2>Four weeks.<br/>One clear launch.</h2><p>Live workshops on Tuesdays, implementation labs on Fridays, and feedback throughout.</p></div><div className="modules">{modules.map((m,i)=><article className={open===i?"active":""} key={m.n}><button onClick={()=>setOpen(open===i?-1:i)} aria-expanded={open===i}><span>{m.n}</span><h3>{m.title}</h3><ChevronDown/></button>{open===i&&<div className="module-body"><p>{m.copy}</p><ul>{m.lessons.map(x=><li key={x}><Check/>{x}</li>)}</ul></div>}</article>)}</div></section>
 <section className="instructor" id="instructor"><div className="portrait"><img src="/maya-chen.png" alt="Maya Chen, fictional LaunchCraft instructor"/><div>12 YEARS<br/>BUILDING LAUNCHES</div></div><div className="bio"><p className="eyebrow">YOUR INSTRUCTOR</p><h2>Maya Chen turns good work into clear offers.</h2><p>After a decade leading campaigns for independent studios and category-defining products, Maya built LaunchCraft to teach the strategic decisions behind launches that feel focused, generous, and unmistakably yours.</p><blockquote>“A launch works when the story, offer, and timing all point in the same direction.”</blockquote><div className="stats"><span><b>46</b> launches led</span><span><b>$8.4m</b> client revenue</span><span><b>6</b> cohorts taught</span></div></div></section>
 <section className="testimonials"><p className="eyebrow">FROM THE STUDIO</p><div className="quote-grid">{testimonials.map(t=><article key={t.name}><Quote/><div className="stars">{[1,2,3,4,5].map(x=><Star key={x}/>)}</div><p>“{t.q}”</p><footer><b>{t.name}</b><span>{t.role}</span></footer></article>)}</div></section>
 <section className="pricing" id="pricing"><div><p className="eyebrow">COHORT 06 ENROLLMENT</p><h2>Your next launch starts here.</h2><p>Enrollment closes when the timer hits zero or the 24-seat studio fills.</p><Countdown/></div><article className="price-card"><span>LAUNCHCRAFT LIVE</span><h3>$790 <small>or 2 × $415</small></h3><ul><li><Check/>4 live strategy workshops</li><li><Check/>4 implementation labs</li><li><Check/>Personal offer feedback</li><li><Check/>Templates and campaign system</li><li><Check/>Lifetime lesson access</li></ul><button className="primary" onClick={()=>setModal(true)}>Reserve your seat <ArrowRight/></button><small>Frontend demonstration—no payment will be processed.</small></article></section>
 </main><footer className="site-footer"><a className="logo" href="#top">LAUNCH<span>CRAFT</span></a><p>Fictional course experience created as a portfolio demonstration.</p><span>© 2026 LaunchCraft</span></footer>
 {modal&&<div className="modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="register-title"><button className="modal-close" onClick={close} aria-label="Close registration"><X/></button>{step<3&&<div className="steps"><span className="active">1</span><i/><span className={step>=2?"active":""}>2</span></div>}{step===1?<><p className="eyebrow">STEP 1 OF 2</p><h2 id="register-title">Save your seat.</h2><label>Name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Your full name"/></label><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" type="email"/></label><button className="primary wide" onClick={next} disabled={!name.trim()||!email.includes("@")}>Continue <ArrowRight/></button></>:step===2?<><p className="eyebrow">STEP 2 OF 2</p><h2 id="register-title">What are you launching?</h2><div className="goal-options">{["A course or cohort","A creative service","A digital product","Still deciding"].map(x=><button className={goal===x?"selected":""} onClick={()=>setGoal(x)} key={x}>{x}<Check/></button>)}</div><button className="primary wide" onClick={next} disabled={!goal}>Complete registration <ArrowRight/></button></>:<div className="success"><span><Check/></span><p className="eyebrow">YOU’RE ON THE LIST</p><h2 id="register-title">Welcome to the studio, {name.split(" ")[0]}.</h2><p>We’ve simulated your registration. In a production version, confirmation and payment details would arrive by email.</p><button className="primary wide" onClick={close}>Done</button></div>}</div></div>}
 </>}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
